"""
Unified Data Models for Multi-Agent Orchestration
==================================================

Pydantic-validated schemas shared across all three orchestration architectures.
Ensures type-safe, structured communication between Planner, Browser, and Critic agents.

These models enforce consistency regardless of the underlying coordination framework
(AutoGen GroupChat, LangGraph StateGraph, or CrewAI Crews).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator


# ─── Enumerations ────────────────────────────────────────────────────────────

class ActionType(str, Enum):
    """Supported browser action types for the skill library."""
    NAVIGATE = "navigate"
    CLICK = "click"
    TYPE_TEXT = "type_text"
    SELECT_OPTION = "select_option"
    SCROLL = "scroll"
    WAIT = "wait"
    SCREENSHOT = "screenshot"
    EXTRACT_TEXT = "extract_text"
    EXTRACT_TABLE = "extract_table"
    API_CALL = "api_call"
    FILE_UPLOAD = "file_upload"
    GOOGLE_SEARCH = "google_search"
    READ_PAGE = "read_page"
    LIST_ELEMENTS = "list_interactive_elements"
    PRESS_KEY = "press_key"
    DOWNLOAD = "download"
    CUSTOM = "custom"


class TaskStatus(str, Enum):
    """Status of a task or subtask within the execution pipeline."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    NEEDS_REPLANNING = "needs_replanning"
    AWAITING_HUMAN = "awaiting_human"
    SKIPPED = "skipped"


class VerificationStatus(str, Enum):
    """Outcome of critic verification."""
    SUCCESS = "success"
    FAILURE = "failure"
    PARTIAL = "partial"
    UNCERTAIN = "uncertain"
    ERROR = "error"


class DOMRepresentationType(str, Enum):
    """DOM distillation strategies following Agent-E methodology."""
    TEXT_ONLY = "text_only"
    INPUT_FIELDS = "input_fields"
    ALL_FIELDS = "all_fields"
    INTERACTIVE_ONLY = "interactive_only"
    SEMANTIC = "semantic"


# ─── Core Data Models ────────────────────────────────────────────────────────

class PlanStep(BaseModel):
    """
    Individual step within a hierarchical task plan.
    Generated by the Planner Agent and consumed by the Browser Agent.
    
    Implements epistemic planning annotations (Krichmar et al., 2025)
    for reasoning about knowledge states and uncertainty.
    """
    step_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    action_type: ActionType
    target: Optional[str] = Field(
        default=None,
        description="CSS selector, URL, or API endpoint target"
    )
    parameters: Dict[str, Any] = Field(default_factory=dict)
    expected_outcome: str = Field(
        description="Natural language description of expected post-condition"
    )
    verification_criteria: Optional[str] = Field(
        default=None,
        description="Specific criteria for the Critic to verify this step"
    )
    depends_on: List[str] = Field(
        default_factory=list,
        description="Step IDs that must complete before this step"
    )
    fallback_action: Optional[str] = Field(
        default=None,
        description="Alternative action if primary action fails"
    )
    epistemic_confidence: float = Field(
        default=0.8,
        ge=0.0,
        le=1.0,
        description="Planner's epistemic confidence in this step (0.0–1.0)"
    )
    max_retries: int = Field(default=2, ge=0, le=5)
    timeout_seconds: float = Field(default=30.0, gt=0)

    @field_validator("epistemic_confidence")
    @classmethod
    def validate_confidence(cls, v: float) -> float:
        return round(v, 3)


class TaskPlan(BaseModel):
    """
    Complete hierarchical task plan produced by the Planner Agent.
    Contains ordered steps with dependency tracking.
    """
    plan_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:12])
    user_request: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    steps: List[PlanStep]
    total_estimated_time: float = Field(
        default=0.0,
        description="Estimated total execution time in seconds"
    )
    complexity_score: float = Field(
        default=1.0,
        ge=0.0,
        le=10.0,
        description="Task complexity assessment (0=trivial, 10=extreme)"
    )
    requires_authentication: bool = False
    requires_api_access: bool = False


class ActionResult(BaseModel):
    """Result from a single Browser Agent action execution."""
    step_id: str
    action_type: ActionType
    success: bool
    output: str = ""
    error: Optional[str] = None
    execution_time: float = Field(
        default=0.0,
        description="Wall-clock time for this action in seconds"
    )
    dom_changes_detected: bool = False
    dom_changes_summary: Optional[str] = None
    screenshot_path: Optional[str] = None
    tokens_consumed: int = 0
    retry_count: int = 0


class VerificationResult(BaseModel):
    """
    Structured output from the Critic Agent's LLM-based verification pipeline.
    
    The Critic analyzes execution traces and DOM states to verify task completion,
    detect anomalies, and generate refinement feedback for the Planner.
    """
    step_id: str
    status: VerificationStatus
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Critic's confidence in the verification outcome"
    )
    issues: List[str] = Field(default_factory=list)
    recommendations: List[str] = Field(default_factory=list)
    dom_state_summary: Optional[str] = None
    expected_vs_actual: Optional[str] = Field(
        default=None,
        description="Comparison between expected outcome and actual state"
    )
    requires_replanning: bool = False
    requires_human_intervention: bool = False
    anomalies_detected: List[str] = Field(default_factory=list)


class ExecutionTrace(BaseModel):
    """
    Complete execution trace for a task, capturing all agent interactions.
    Stored in PostgreSQL for post-execution analysis and system improvement.
    """
    trace_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    task_plan: TaskPlan
    action_results: List[ActionResult] = Field(default_factory=list)
    verification_results: List[VerificationResult] = Field(default_factory=list)
    total_execution_time: float = 0.0
    total_tokens_consumed: int = 0
    total_steps: int = 0
    reasoning_steps: int = 0
    tool_steps: int = 0
    replanning_cycles: int = 0
    human_interventions: int = 0
    final_status: TaskStatus = TaskStatus.PENDING
    started_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None


# ─── Agent State Models ──────────────────────────────────────────────────────

class BeliefState(BaseModel):
    """
    Shared belief state maintained across all agents via TB-CSPN.
    Implements dynamic topic-based coordination and human-in-the-loop intervention.
    
    Reference: Borghoff et al. (2025) — Topic-Based Communication-Space Petri Nets
    """
    task_context: str = ""
    current_url: Optional[str] = None
    current_page_title: Optional[str] = None
    dom_representation: Optional[str] = None
    dom_type: DOMRepresentationType = DOMRepresentationType.TEXT_ONLY
    action_history: List[ActionResult] = Field(default_factory=list)
    plan_history: List[TaskPlan] = Field(default_factory=list)
    epistemic_confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Global epistemic confidence across the task"
    )
    active_topics: List[str] = Field(
        default_factory=list,
        description="TB-CSPN active communication topics"
    )
    human_feedback: List[str] = Field(default_factory=list)
    error_count: int = 0
    max_errors_before_human: int = 3


class AgentMessage(BaseModel):
    """Structured message for inter-agent communication."""
    sender: str = Field(description="Agent name: planner | browser | critic | manager")
    receiver: str
    content: str
    message_type: str = Field(
        default="action",
        description="Type: action | feedback | verification | error | human_request"
    )
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    plan_step: Optional[PlanStep] = None
    action_result: Optional[ActionResult] = None
    verification_result: Optional[VerificationResult] = None


# ─── Evaluation Models ───────────────────────────────────────────────────────

class BenchmarkResult(BaseModel):
    """Result from a single benchmark task execution."""
    task_id: str
    task_category: str = Field(description="travel_booking | academic_research | ecommerce")
    framework: str = Field(description="pydantic_autogen | langgraph_autogen | crewai_langchain | single_agent")
    success: bool
    completion_time: float = Field(description="Seconds from start to final output")
    total_tokens: int = 0
    input_tokens: int = 0
    output_tokens: int = 0
    cost_usd: float = 0.0
    total_steps: int = 0
    reasoning_steps: int = 0
    tool_steps: int = 0
    cpu_seconds: float = 0.0
    memory_mb: float = 0.0
    network_mb: float = 0.0
    human_interventions: int = 0
    replanning_cycles: int = 0
    error_messages: List[str] = Field(default_factory=list)
    execution_trace: Optional[ExecutionTrace] = None
